### ISSUE TITLE
It does not work on Raspberry Pi (Raspbian)

### ISSUE THREAD

**Issue by Fran008** [VeNoMouS/cloudflare-scrape-js2py#10]
First of all, I want to thank you for such a great and updated program. I have tested on Debian and it works flawlessly. But when I install it in various Raspberries (Pi Zero, Pi 3...) it just doesn't work. It loads normal webs correctly, but when the page implements Cloudflare it just can't bypass. Raspberries' OS is Raspbian.

**Comment by VeNoMouS** [comment]
Can you give some more information please"? like the payload of the html from cf?

**Comment by Fran008** [comment]
The problem comes when calling the function:

 cfscrape.get_cookie_string("http://thebot.net")

The outgoing message sais:

ERROR:root:'http://thebot.net' returned an error. Could not collect tokens.

**Comment by VeNoMouS** [comment]
@Fran008 using my dev branch and python 2 (as js2py breaks in py3 atm https://github.com/PiotrDabkowski/Js2Py/issues/156) 

Try

```
#!/usr/bin/python

from lib import cfscrape
from lib import requests
from pprint import pprint
import os
import sys
import re
from base64 import b64decode
class Test():
    def __init__(self):
            self.site_url = "http://thebot.net"
            self.session = requests.session()
            self.funcName = lambda n=0: sys._getframe(n + 1).f_code.co_name + "()"
    
    def _cloudFlare(self, response):
            cf = cfscrape.create_scraper(sess=self.session)
    
            if cf.is_cloudflare_challenge(response):
                print("{} requested URL - {}, encounted CloudFlare DDOS Protection.. Bypassing.".format(self.funcName(), response.url))
    
                response = cf.get(self.site_url, timeout=30)
            
                if not cf.is_cloudflare_challenge(response):
                    return (True, True)
    
                return (True, False)
    
            return (False, True)
        
        
    def test(self):
        ret = self.session.get(self.site_url, timeout=30)
        if (True, True) == self._cloudFlare(ret):
            print("{} CloudFlare DDOS Protection.. Bypassed successfully.".format(self.funcName()))
            ret = self.session.get(self.site_url, timeout=30)
            print(ret.content)


Test().test()```

**Comment by Fran008** [comment]
When I execute this code against a normal page, it gives NO output.

When I execute this code against "http://thebot.net", it gives:

_cloudFlare() requested URL - http://thebot.net/, encounted CloudFlare DDOS Protection.. Bypassing.
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

Traceback (most recent call last):
  File "./fran", line 41, in <module>
    Test().test()
  File "./fran", line 35, in test
    if (True, True) == self._cloudFlare(ret):
  File "./fran", line 23, in _cloudFlare
    response = cf.get(self.site_url, timeout=30)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 73, in request
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 109, in solve_cf_challenge
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 177, in solve_challenge
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/evaljs.py", line 115, in eval_js
    return e.eval(js)
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/evaljs.py", line 188, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/evaljs.py", line 183, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/base.py", line 956, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/base.py", line 1470, in call
    return Js(self.code(*args))
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/host/jseval.py", line 45, in Eval
    executor(py_code)
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/host/jseval.py", line 51, in executor
    exec (code, globals())
  File "<string>", line 69, in <module>
  File "<string>", line 68, in PyJs_LONG_27_
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/base.py", line 956, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/base.py", line 1470, in call
    return Js(self.code(*args))
  File "<string>", line 66, in PyJs_anonymous_26_
  File "/usr/local/lib/python2.7/dist-packages/Js2Py-0.60-py2.7.egg/js2py/base.py", line 1001, in callprop
    '%s is not a function' % cand.typeof())
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function

**Comment by VeNoMouS** [comment]
@Fran008 cf changed their algo yesterday.. use the dev branch for now.

**Comment by VeNoMouS** [comment]
@Fran008 production is good :)

**Comment by Fran008** [comment]
Here are my tests with the updated version:

1- The code you gave me two days ago works ALWAYS in Raspberry Pi. These are good news!!

2- BUT when I try to get the cookies with function "cfscrape.get_cookie_string('http://thebot.net')" it just doesn't work in Raspberry (it works fine in other systems).

3- This function works WITH SOME WEBS in Raspberry, for example accessing this site: "cfscrape.get_cookie_string('http://tradeogre.com')". That means that the function is working properly... but in some webs it just crash.

**Comment by Fran008** [comment]
The error sais:

_cloudFlare() requested URL - http://thebot.net/, encounted CloudFlare DDOS Protection.. Bypassing.
ERROR:root:'http://thebot.net' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "./fran", line 51, in <module>
    Test().test()
  File "./fran", line 45, in test
    if (True, True) == self._cloudFlare(ret):
  File "./fran", line 25, in _cloudFlare
    cookie_value, user_agent = cf.get_cookie_string("http://thebot.net")
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 257, in get_cookie_string
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 228, in get_tokens
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 74, in request
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 128, in solve_cf_challenge
  File "/usr/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by VeNoMouS** [comment]
Is there any reason you're calling "get_cookie_string"?

**Comment by VeNoMouS** [comment]
@Fran008 want to give it a try now?

```
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lib import cfscrape
>>> cfscrape.get_cookie_string('http://thebot.net')
('__cfduid=d14b230d731b7bc69825798b178d91c2a1554422873; cf_clearance=b1389d36aa0fdbe18fc000c920e754e05abe6771-1554422881-604800-150', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0')
>>> cfscrape.get_cookie_string('http://tradeogre.com')
('__cfduid=d444c1c0309160f01b753359ea143d7941554422900; cf_clearance=80646933840b70a9fe0705b14bad6f7d054a8c45-1554422904-86400-150', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0')
>>>
```

```
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lib import cfscrape
>>> cfscrape.get_cookie_string('http://thebot.net')
('cf_clearance=e25b11a3e9c544543dfa4497a4c6c17549b7eaf3-1554422934-604800-150; __cfduid=d62e48608600bbc63fcc29ce5018903751554422926', 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53')
>>> cfscrape.get_cookie_string('http://tradeogre.com')
('cf_clearance=af247fca502d666e68dc61cd8c002b255fed5cd4-1554422941-86400-150; __cfduid=da5bc9dc327df3ad46f0a24b97aa921701554422937', 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53')
>>>
```

**Comment by Fran008** [comment]
It's working now in Raspbian/Raspberry!!!

But just for your information: it only works with https in this web (https://thebot.net), it fails with http.

**Comment by HawkLiking** [comment]
On linux it’s working in both case

For information, after resolving the cf challenge, thebot.net redirects (301 permanently) the http request to https. It works on debian/ubuntu but maybe not well in raspbian... ? Seems weird

Can you give the stack trace (error) please @Fran008 ?

**Comment by Fran008** [comment]
I confirm it, too (for this web, thebot.net):

http in PC Linux: OK
https in PC Linux: OK
https in Raspberry: OK
http in Raspberry: KO

This is the trace:

_cloudFlare() requested URL - http://thebot.net/, encounted CloudFlare DDOS Protection.. Bypassing.
ERROR:root:'http://thebot.net' returned an error. Could not collect tokens.
Traceback (most recent call last):
  File "./fran", line 51, in <module>
    Test().test()
  File "./fran", line 45, in test
    if (True, True) == self._cloudFlare(ret):
  File "./fran", line 25, in _cloudFlare
    cookie_value, user_agent = cfscrape.get_cookie_string(self.site_url)
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 275, in get_cookie_string
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 246, in get_tokens
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 93, in request
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 146, in solve_cf_challenge
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 86, in request
  File "build/bdist.linux-armv7l/egg/cfscrape/__init__.py", line 60, in is_cloudflare_challenge
ValueError: Captcha

**Comment by HawkLiking** [comment]
Looks like you’re having the captcha challenge in http on raspbian (not only js challenge)... 
Have you made all your tests on the same public ip address ?

**Comment by VeNoMouS** [comment]
```
Querying(1) http://thebot.net/
('cf_clearance=33aae18f3af78eed0b99c60f2e0fe1887501da27-1554453262-604800-150; __cfduid=df9858f9de3838408f747df0c7d07cac91554453257', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0')
Querying(2) http://thebot.net/
('cf_clearance=10057b5829850232574ddc6cc22a60f45255dfd8-1554453273-604800-150; __cfduid=df73d54d4674d8f37883a0d7f4f33a6d41554453264', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36')
Querying(3) http://thebot.net/
('cf_clearance=a42d029577e8132c32812bfb1a07dd3144f25989-1554453279-604800-150; __cfduid=d7e240f716955e140974aa82ad08646a01554453275', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0')
Querying(4) http://thebot.net/
('cf_clearance=d5a502fa57bcf0d0d86c9f0d31bfc2cb39b98c5d-1554453286-604800-150; __cfduid=d8e992000cbf0879c5d4b711a77b29e401554453282', 'Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Build/NPPS25.137-93-8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36')
Querying(5) http://thebot.net/
('cf_clearance=81942bc08a2135af9f5d22b75effe2dcd07142f0-1554453292-604800-150; __cfduid=d9b584fd8a23860624f91655f978a020a1554453288', 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53')
```

```
#!/usr/bin/python
from lib import cfscrape

urls = [
   'http://thebot.net/'
   #'https://www.japscan.to/search/',
   #'http://gnula.nu/',
   #'https://coinmarketcap.com/currencies/bitcoin/',
   #'http://javlibrary.com/cn/',
   #'https://movcr.cc',
   #'http://scene-rls.net',
   #'https://search.rlsbb.ru'
]

for i in range(1, 6):
   for url in urls:
      print("Querying({}) {}".format(i, url))
      scraper = cfscrape.create_scraper()
      print(scraper.get_cookie_string(url))
```

**Comment by Fran008** [comment]
Mmm... that explains one thing.

The fact is that THE FIRST TIME I tested http in Raspberry, it worked! From now on, it only worked on https.

But from the same IP and with Linux, it enters always with http. First time, second time, n time.

**Comment by VeNoMouS** [comment]
```
_cloudFlare() requested URL - http://thebot.net/, encounted CloudFlare DDOS Protection.. Bypassing.
test() CloudFlare DDOS Protection.. Bypassed successfully.
< GET / HTTP/1.1
< Host: thebot.net
< Connection: keep-alive
< Accept-Encoding: gzip, deflate
< Accept: */*
< User-Agent: python-requests/2.10.0
< Cookie: cf_clearance=31195d3f83a7b10abe2c9d296a9193bd7fff38f5-1554453669-604800-150; __cfduid=d64ef559f12e14b0ef90da874177399601554453665
<

> HTTP/1.1 301 Moved Permanently
> Date: Fri, 05 Apr 2019 08:41:12 GMT
> Content-Type: text/html
> Transfer-Encoding: chunked
> Connection: keep-alive
> Location: https://thebot.net/
> Server: cloudflare
> CF-RAY: 4c2a38b6b8a81914-AKL
>
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
< GET / HTTP/1.1
< Host: thebot.net
< Connection: keep-alive
< Accept-Encoding: gzip, deflate
< Accept: */*
< User-Agent: python-requests/2.10.0
< Cookie: xf_csrf=Q18g5kdTzbW-B8vC; cf_clearance=31195d3f83a7b10abe2c9d296a9193bd7fff38f5-1554453669-604800-150; __cfduid=d64ef559f12e14b0ef90da874177399601554453665
<

> HTTP/1.1 200 OK
> Date: Fri, 05 Apr 2019 08:41:13 GMT
> Content-Type: text/html; charset=utf-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> X-Frame-Options: SAMEORIGIN
> X-Content-Type-Options: nosniff
> Last-Modified: Fri, 05 Apr 2019 08:41:13 GMT
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> Cache-Control: private, no-cache, max-age=0
> Vary: Accept-Encoding
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Server: cloudflare
> CF-RAY: 4c2a38ba6aafa41d-AKL
> Content-Encoding: gzip
>
<!DOCTYPE html>
<html id="XF" lang="en-US" dir="LTR" style="font-size: 62.5%;" data-app="public" data-template="forum_list" data-container-key="" data-content-key="" data-logged-in="false" data-cookie-prefix="xf_" class="has-no-js template-forum_list  uix_page--fixed uix_hasSectionLinks  uix_hasPageAction" data-run-jobs="">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Make Money Online Forum</title>
<link rel="canonical" href="https://thebot.net/" />
<link rel="alternate" type="application/rss+xml" title="RSS feed for Make Money Online Forum" href="/forums/-/index.rss" />
<meta property="og:site_name" content="Make Money Online Forum" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Make Money Online Forum" />
<meta property="twitter:title" content="Make Money Online Forum" />
<meta property="og:url" content="https://thebot.net/" />
<meta name="theme-color" content="#202020" />
<meta name="msapplication-TileColor" content="#202020">
<link rel="preload" href="/styles/fonts/fa/fa-regular-400.woff2" as="font" type="font/woff2" crossorigin="anonymous" />
<link rel="preload" href="/styles/fonts/fa/fa-solid-900.woff2" as="font" type="font/woff2" crossorigin="anonymous" />
<link rel="preload" href="/styles/fonts/fa/fa-brands-400.woff2" as="font" type="font/woff2" crossorigin="anonymous" />
<link rel="stylesheet" href="/css.php?css=public%3Anormalize.css%2Cpublic%3Acore.less%2Cpublic%3Aapp.less&amp;s=12&amp;l=1&amp;d=1552853746&amp;k=138d19067e8958d887e95aa022691ac858b4c69e" />
<link rel="stylesheet" href="/styles/uix_dark/fonts/icons/material-icons/css/materialdesignicons.min.css" />
<link rel="stylesheet" href="/css.php?css=public%3Anode_list.less%2Cpublic%3Anotices.less%2Cpublic%3Asiropu_ads_manager_ad.less%2Cpublic%3Asiropu_ads_manager_slick.less%2Cpublic%3Axc_user_activity.less%2Cpublic%3Aextra.less&amp;s=12&amp;l=1&amp;d=1552853746&amp;k=a19a39646cda83e0466b845ba417815b95722d8d" />
<link href='//fonts.googleapis.com/css?family=Roboto:300,400,500,600,700' rel='stylesheet' type='text/css'>
<script src="/js/xf/preamble.min.js?_v=57d28716"></script>
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="icon" type="image/png" href="https://thebot.net/favicon.ico" sizes="32x32" />
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-15931399-1"></script>
<script>
```

ETC...

```
#!/usr/bin/python

from lib import cfscrape
from lib import requests
from pprint import pprint
import os
import sys
import re
from base64 import b64decode
from requests_toolbelt.utils import dump
class Test():
    def __init__(self):
            self.site_url = "http://thebot.net"
            self.session = requests.session()
            self.funcName = lambda n=0: sys._getframe(n + 1).f_code.co_name + "()"
    
    def _cloudFlare(self, response):
            cf = cfscrape.create_scraper(sess=self.session)
            cf.set_cloudflare_challenge_delay(0)
    
            if cf.is_cloudflare_challenge(response):
                print("{} requested URL - {}, encounted CloudFlare DDOS Protection.. Bypassing.".format(self.funcName(), response.url))
    
                response = cf.get(self.site_url, timeout=30)
            
                if not cf.is_cloudflare_challenge(response):
                    return (True, True)
    
                return (True, False)
    
            return (False, True)
        
        
    def test(self):
        ret = self.session.get(self.site_url, timeout=30)
        if (True, True) == self._cloudFlare(ret):
            print("{} CloudFlare DDOS Protection.. Bypassed successfully.".format(self.funcName()))
            ret = self.session.get(self.site_url, timeout=30)
            data = dump.dump_all(ret)
            print(data)

Test().test()
```

**Comment by VeNoMouS** [comment]
Works fine both ways... are you gents using py2 or py3?

**Comment by Fran008** [comment]
Python2, and Raspberry Pi 3.

In Linux both ok. In Raspberry, same IP, ok with https but ko since second time I entered.

**Comment by HawkLiking** [comment]
@Fran008 try it with the Test class @VeNoMouS just post, and give all the output, maybe it comes from specific header or cookies...

**Comment by VeNoMouS** [comment]
@Fran008 can you edit your cfscrape code... add

```
from requests_toolbelt.utils import dump
```

and in the `request` function after the line `resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)`

Add..

```
data = dump.dump_all(resp)
print(data)
```

then run your code again, and email me all the output please.

**Comment by VeNoMouS** [comment]
@Fran008 also are you sure you are running the latest version of the library?

**Comment by Fran008** [comment]
Which library?

I guess your program install it automatically, but in any case I have also tried:

git clone https://github.com/PiotrDabkowski/Js2Py
cd Js2Py
sudo python setup.py install

I have installed requests_toolbelt.utils too, but no new error messages come out.

**Comment by VeNoMouS** [comment]
??? im referring to cfscrape ... from .. https://github.com/VeNoMouS/cloudflare-scrape-js2py/

**Comment by Fran008** [comment]
Yeah, me too of course.

**Comment by Fran008** [comment]
I have installed --again-- last version from https://github.com/VeNoMouS/cloudflare-scrape-js2py/ and everything remains the same.

**Comment by VeNoMouS** [comment]
@Fran008 how did you "install"?

**Comment by Fran008** [comment]
git clone https://github.com/VeNoMouS/cloudflare-scrape-js2py
cd cloudflare-scrape-js2py
sudo python setup.py install

**Comment by VeNoMouS** [comment]
I would manually delete the installed version just incase you have Anorov's original library.

**Comment by Fran008** [comment]
sudo git clone https://github.com/Anorov/cloudflare-scrape
cd cloudflare-scrape
sudo python setup.py install --record files.txt
cat files.txt | xargs sudo rm -rf
cd ..
git clone https://github.com/VeNoMouS/cloudflare-scrape-js2py
cd cloudflare-scrape-js2py
sudo python setup.py install

Once done the uninstallation and installation... same error.

**Comment by VeNoMouS** [comment]
@Fran008 replace the __init__.py with https://pastebin.com/FwC7vdqK

**Comment by Fran008** [comment]
It works like a charm!!

You're awesome, thank you for your great program and please keep it updated ;)

**Comment by VeNoMouS** [comment]
@Fran008 lol .. thats just with some debug in it... that's all that changed from the normal install!?!?

**Comment by VeNoMouS** [comment]
I might just bump the version to `2.0.0`

**Comment by Fran008** [comment]
Sorry!!

You're right. What I saw is not the final page... they are your new messages.

**Comment by Fran008** [comment]
The error remains the same :(

**Comment by VeNoMouS** [comment]
Can you please email the debug output to my email on my profile... cheers.

**Comment by Fran008** [comment]
Done! I have to drive, so I'll be out for a while.

**Comment by VeNoMouS** [comment]
Got it cheers @Fran008 let me read over this.

**Comment by HawkLiking** [comment]
Yeah you should bump to 2.0.0 and bump version more often

If you stay on 1.9.5, making a "git pull" and "python setup.py install" will not update cfscrape, i have to make a "pip uninstall cfscrape" each time (not really a problem if you know)

**Comment by VeNoMouS** [comment]
@Fran008 for some reason your UA is out of order on the Challenge solve post..

```

< GET /cdn-cgi/l/chk_jschl?jschl_answer=95.2984058696&s=839d66556e4380586bc9b0385deabc4c6384c7e0-1554460972-1800-AbZaMOY5sp5lr9PQDBTarHDfrKjc%2Bsiu1lyqpdpLsbIDLSo1ThICCMnH%2BkqDy15SUXeYX6Dx%2BVwWCrPKVUfl%2BGF61XIj%2BmZ94eRXmYd72yO%2BLkFpsMYW9dcjn6Rb4N%2FoMw%3D%3D&jschl_vc=5dcaae333b901573e82005f378d17022&pass=1554460976.258-huZGp1QAF8 HTTP/1.1
< Host: thebot.net
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Upgrade-Insecure-Requests: 1
< Connection: close
< Referer: http://thebot.net/
< Cookie: __cfduid=d6c68a6b35533254d442e874e2400bdc21554460972
< User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
```

the UA should not be the last..

**Comment by VeNoMouS** [comment]
Even your intial GET is out of order

```
< GET / HTTP/1.1
< Host: thebot.net
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
< Connection: close
< Upgrade-Insecure-Requests: 1
```

something is wrong with your OrderedDict, what version is your python?? like the actual version???

**Comment by VeNoMouS** [comment]
Simple test run

```
from collections import OrderedDict
ourdict = OrderedDict([('one', 'one') , ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six')])
ourdict 
```

what is the output?

it __should__ be 

```
OrderedDict([('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six')])
```

**Comment by VeNoMouS** [comment]
Either...

a) OrderedDict isn't honoring the order... 
b) requests library is out isn't honoring the order... 

I would check the version on collections && requests library's.

**Comment by Fran008** [comment]
Python version is 2.7.9

Requests library seems up to date.

I have to do the test. Later in home.

**Comment by Fran008** [comment]
"sudo pip install ordereddict" made no changes.

**Comment by VeNoMouS** [comment]
`ordereddict` is part of `collections` module... @Fran008 what if you use python3?

**Comment by VeNoMouS** [comment]
@Fran008 can you please run

```
>>> from requests import __version__
>>> __version__
```

**Comment by Fran008** [comment]
Version is 2.4.3

**Comment by VeNoMouS** [comment]
Theres your issue... https://stackoverflow.com/questions/17239952/python-http-request-with-controlled-ordering-of-http-headers

OrderDict for headers was fixed in `2.9.2` upgrade you're requests library

**Comment by VeNoMouS** [comment]
I've also pushed fix for install to meet minimum of 2.9.2 or higher.

**Comment by Fran008** [comment]
WOW! It finally works, with the dev branch!!

Thank you so much. Keep up the good work.

**Comment by VeNoMouS** [comment]
Np mate, glad you got there in the end :)

**Comment by VeNoMouS** [comment]
@pro-src tagging you in so you are aware with requests version and header order issue.
