### ISSUE TITLE
ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by Krylanc3lo** [VeNoMouS/cloudflare-scrape-js2py#14]
Hello,

Atob error is back :(
Does anyone experience the same issue ?

  File "/var/lib/jenkins/.local/lib/python3.6/site-packages/js2py/base.py", line 1079, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
js2py.internals.simplex.JsException: ReferenceError: atob is not defined

**Comment by pro-src** [comment]
@Krylanc3lo Use python2 if possible. There are some open issues regarding js2py and python3.

**Comment by Krylanc3lo** [comment]
I will try and let you know. thanks for the notice

**Comment by VeNoMouS** [comment]
also try the dev branch if you using python 2 ... its got a little re-jig happening :)

**Comment by VeNoMouS** [comment]
dev branch also just updated for latest algo change .

**Comment by VeNoMouS** [comment]
@Krylanc3lo please confirm dev branch is ok?

**Comment by Krylanc3lo** [comment]
Hello,
Thank for the feedback. Sorry I just got back from work. I will test right away and let you know.

**Comment by Krylanc3lo** [comment]
Nevermind, it seems to be python2. I will update my script to use python2 then.
I will keep you posted

**Comment by pro-src** [comment]
@Krylanc3lo I think py3 support will be working soon.

**Comment by VeNoMouS** [comment]
@Krylanc3lo i've just done a push, py3 should not be good.

**Comment by Krylanc3lo** [comment]
OK I will try again then :)

Thank you!

**Comment by Krylanc3lo** [comment]
so I did download the new repo, did a python3 setup.py install and launch the same test code than before (the function you did provide)

I am getting this error:
  File "/usr/local/lib/python3.6/dist-packages/js2py/base.py", line 938, in callprop
    raise  MakeError('TypeError','%s is not a function'%cand.typeof())
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function

**Comment by VeNoMouS** [comment]
uhh check the cfscrape package __init__.py file on line ~157 prob in your `/usr/local/lib/python3.6/dist-packages/cfscrape/` dir and see if it says ` var g = String.fromCharCode;`  if it doesnt just delete /usr/local/lib/python3.6/dist-packages/cfscrape/ and install it again.

**Comment by Krylanc3lo** [comment]
Indeed it doesn't. I deleted both in /usr & ~./local... reinstall and I got a new  error.. haha
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 53, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

I will debug :)

**Comment by VeNoMouS** [comment]
I have no idea what that's about...  i don't think that's being generated by my library? 

Have you got test code you can share? or perhaps the url you're trying to access?

**Comment by VeNoMouS** [comment]
@Krylanc3lo they changed the js slightly... that one line into the js was all that was required.

**Comment by VeNoMouS** [comment]
@Krylanc3lo so your all good and i can close this?

**Comment by pro-src** [comment]
For future reference, it's a lot easier to just use ***pipenv*** (pip with perks)
https://pipenv.readthedocs.io/en/latest/basics/
```sh
pip install pipenv

cd my-project
pipenv --python 3
pipenv install "git@github.com/VeNoMouS/cloudflare-scrape-js2py#dev"
pipenv shell
```

**Comment by Krylanc3lo** [comment]
yes I just finished the tests, all good, as usual with your help @VeNoMouS  (and tanks @pro-src for the tips). 
I am closing this thread ^^

**Comment by pro-src** [comment]
@Krylanc3lo I updated those tips... Fixed wrong syntax for installing from git.

**Comment by VeNoMouS** [comment]
@Krylanc3lo team effort mate :)
