### ISSUE TITLE
Implement session when session not passed

### ISSUE THREAD

**Issue by VeNoMouS** [VeNoMouS/cloudflare-scrape-js2py#16]
if a session isn't passed on the class initialization, create a session with inside the class. 

@pro-src what do you think?

**Comment by pro-src** [comment]
I think that the scraper is already an instance of `Session` and that `create_scraper` only copies attributes from the session to the new session that it creates.

**Comment by pro-src** [comment]
Session is the base class of CloudflareScraper
https://github.com/VeNoMouS/cloudflare-scrape-js2py/blob/5a3b966d5daca7dd6bc43f9de44eabfa8bf3f1d6/cfscrape/__init__.py#L44

**Comment by VeNoMouS** [comment]
I don't think its passing the Super session over correctly when calling without passing an initial session... need to debug. 

refer #11

**Comment by pro-src** [comment]
@VeNoMouS then it's the attributes that are being copied over that solves the problem and the problem/solution lies in the class constructor.

**Comment by VeNoMouS** [comment]
Project has been superseded by my other project ["cloudscraper"](https://pypi.org/project/cloudscraper/) the new git repo can be found [here](https://github.com/VeNoMouS/cloudscraper).
