### ISSUE TITLE
CF new error

### ISSUE THREAD

**Issue by sennz** [VeNoMouS/cloudflare-scrape-js2py#21]
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

Traceback (most recent call last):
    html = scraper.get(iurl, cookies=cj, headers=self.hdr).content
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "h:\python\cfscrape.py", line 91, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "h:\python\cfscrape.py", line 135, in solve_cf_challenge
    params['jschl_answer'] = self.solve_challenge(body, domain)
  File "h:\python\cfscrape.py", line 209, in solve_challenge
    result = context.eval(js)
  File "c:\Python27\lib\site-packages\js2py\evaljs.py", line 188, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "c:\Python27\lib\site-packages\js2py\evaljs.py", line 183, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "c:\Python27\lib\site-packages\js2py\base.py", line 956, in __call__
    return self.call(self.GlobalObject, args)
  File "c:\Python27\lib\site-packages\js2py\base.py", line 1470, in call
    return Js(self.code(*args))
  File "c:\Python27\lib\site-packages\js2py\host\jseval.py", line 17, in Eval
    py_code = translate_js(code.to_string().value, '')
  File "c:\Python27\lib\site-packages\js2py\translators\translator.py", line 65, in translate_js
    parsed = parser.parse(js)  # js to esprima syntax tree
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 2863, in parse
    program = self.parseProgram();
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 2834, in parseProgram
    body = self.parseScriptBody()
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 2823, in parseScriptBody
    statement = self.parseStatementListItem();
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 1989, in parseStatementListItem
    return self.parseStatement();
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 2557, in parseStatement
    return self.parseReturnStatement(node);
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 2360, in parseReturnStatement
    self.tolerateError(Messages.IllegalReturn);
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 984, in tolerateError
    return self.throwError(messageFormat, *args)
  File "c:\Python27\lib\site-packages\pyjsparser\parser.py", line 981, in throwError
    raise self.createError(self.lastLineNumber, self.lastIndex, msg);
js2py.internals.simplex.JsException: SyntaxError: Line 10: Illegal return statement

**Comment by BarryThrill** [comment]
I realized I have the same issue: Here is the picture of the following issues to make it easier to see
![cloudflare](https://user-images.githubusercontent.com/15836342/55868649-2b7e8280-5b85-11e9-97a8-5a9f066771eb.png)
![hehe2](https://user-images.githubusercontent.com/15836342/55868651-2cafaf80-5b85-11e9-9fe6-03385a45f306.png)
![saved](https://user-images.githubusercontent.com/15836342/55868653-2d484600-5b85-11e9-8089-9ffd10181288.png)

following page is https://www.afew-store.com/en/ for me.

**Comment by FrancHR** [comment]
SyntaxError: Line 10: Illegal return statement

```
 /usr/lib/python2.7/logging/__init__.py:882 emit ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.
 func:  SyntaxError: Line 10: Illegal return statement
```

**Comment by VeNoMouS** [comment]
@BarryThrill open up a fresh ticket please, its nothing to do with the current...

**Comment by VeNoMouS** [comment]
@sennz what version of the cfscrape are you using?
```
import cfscrape
cfscrape.__version__
```

**Comment by VeNoMouS** [comment]
@sennz can you please grab dev branch 2.0.2 

```
import cfscrape
scraper = cfscrape.create_scraper()
scraper.debug = True
scraper.get('yoururlhere')
```

and email me the debug output please..

cheers.

**Comment by sennz** [comment]
2.0.1

**Comment by sennz** [comment]
Emailed output.

Cheers

**Comment by FrancHR** [comment]
I forget to say, version 2.0.1, python 2.7
I have tried from DEV branch, version 2.0.2. But i can't use, for now because of requests_toolbelt.

Edit:
installed requests_toolbelt from pip and i have this simple return, nothing more:
`/usr/lib/python2.7/logging/__init__.py:882 emit ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.`

Anyway requests-toolbelt is not solution for me. I hope you can solve the challenge without that.

**Comment by VeNoMouS** [comment]
@sennz I don't see any email from you as of yet...

**Comment by VeNoMouS** [comment]
#22 could be related, stay tuned

**Comment by Krylanc3lo** [comment]
Hello,
I have the same error message, let me know if you want the output, if it can help

**Comment by VeNoMouS** [comment]
@Krylanc3lo yea if you don't mind, cheers just email it to me

**Comment by sennz** [comment]
I emailed to venom at gen-x.co.nz

**Comment by VeNoMouS** [comment]
@krylanc3lo i meant ...

using dev branch 2.0.2

and using..

```
import cfscrape
scraper = cfscrape.create_scraper()
scraper.debug = True
scraper.get('yoururlhere')
```

**Comment by VeNoMouS** [comment]
> I emailed to venom at gen-x.co.nz from my gmail

hrrmmm never got one from you.

**Comment by VeNoMouS** [comment]
@sennz just got it

**Comment by VeNoMouS** [comment]
Ok can you ya'll test out dev branch 2.0.3 .... @FrancHR i've accounted for you lack of library you should be ok moving forward...

**Comment by FrancHR** [comment]
I have sent e-mail to you with output of 2.0.3

**Comment by VeNoMouS** [comment]
@FrancHR your js2py is out of date... upgrade it please.

**Comment by FrancHR** [comment]
I did it, to 0.60, but now i have a lot wrong import problems in js2py. grr....
Ok, I need to study this first and see what is wrong.

**Comment by VeNoMouS** [comment]
Did you upgrade via pip? `pip install --upgrade js2py`...

**Comment by FrancHR** [comment]
Yes, i'm.

Update;
i returned to my old js2py version, and then i removed security feature for initial test, and everything is ok now. The CF challange is passed.
Version 2.0.3

**Comment by VeNoMouS** [comment]
thanks @FrancHR

**Comment by VeNoMouS** [comment]
Upgrade your shit ;P

**Comment by VeNoMouS** [comment]
Anyway before I close off, its 2.0.3 is in master now anyway

**Comment by VeNoMouS** [comment]
@sennz can I close this ticket off?

**Comment by Krylanc3lo** [comment]
Thanks a lot! As usual it works  perfectly :)

**Comment by sennz** [comment]
Sorry for the late reply. It is working. Thanks @VeNoMouS
