### ISSUE TITLE
CF - Potential memory leak?

### ISSUE THREAD

**Issue by BarryThrill** [VeNoMouS/cloudflare-scrape-js2py#23]
Hello once again!

I have realized that since the update of 2.0.3 that everytime I am running the package of "import cfscrape" it automatic takes extra atleast 100mb from RAM to run the code.

You do know in a way how my program works but however I tested a site that doesn't uses cloudflare and also site that uses cloudflare and both gave me same result. 

Basically I tried to see what the issue was and as soon as I imported cfscrape it automatic took me another 100mb like the picture below. (The code is exactly the same, just that one is using requests.get and the other one is using cfscrape.get)

![save](https://user-images.githubusercontent.com/15836342/55940391-511c9200-5c40-11e9-8f69-a3ca55d178ac.png)

I dont know what I can do to debug it more but maybe if someone here checks on their side to see if its not a fault on my side?

**Comment by VeNoMouS** [comment]
My guess would be js2py but I need to investigate further to prove it.

**Comment by BarryThrill** [comment]
> My guess would be js2py but I need to investigate further to prove it.

Let me know if you need any help! :)

**Comment by VeNoMouS** [comment]
@BarryThrill 

a simple script of

```
#!/usr/bin/python

import js2py
```

and running that with valgrind shows us

```
==30724== HEAP SUMMARY:
==30724==     in use at exit: 1,281,479 bytes in 431 blocks
==30724==   total heap usage: 35,563 allocs, 35,132 frees, 158,893,439 bytes allocated
==30724==
==30724== LEAK SUMMARY:
==30724==    definitely lost: 0 bytes in 0 blocks
==30724==    indirectly lost: 0 bytes in 0 blocks
==30724==      possibly lost: 1,072 bytes in 2 blocks
==30724==    still reachable: 1,280,407 bytes in 429 blocks
==30724==         suppressed: 0 bytes in 0 blocks
==30724== Rerun with --leak-check=full to see details of leaked memory
```

so that is where 158mb of your memory is being used ... you need to raise this @PiotrDabkowski on his js2py repo https://github.com/PiotrDabkowski/Js2Py ....

imho i'm not sure why it would require such a large memory footprint on an import...
