### ISSUE TITLE
Page not completely scrapped

### ISSUE THREAD

**Issue by Krylanc3lo** [VeNoMouS/cloudflare-scrape-js2py#27]
Hello,

I am encountering a very weird issue. I am trying to scrap https://www.japscan.to and from time to time (~ 20/30%), the html code the script returns does not contain some lines like:

```
<span class="badge badge-primary">VUS</span>
<span class="badge badge-primary">SPOILER</span>
```
 
I am under impression that they are loaded a little bit after and the script is maybe not waiting enough.

Anyone already had this issue ?

Thank you!

**Comment by VeNoMouS** [comment]
@Krylanc3lo what do you mean not wiating enough?!? lol html && http/1.1 does not work that way.

**Comment by Krylanc3lo** [comment]
I know it is why I find it very weird. When I scrap the page, those lines do not appear each time while they are on the page when I am using the browser. I do not understand how it is possible.

**Comment by pro-src** [comment]
@Krylanc3lo General tech support is not provided here. This is ***not*** stackoverflow and this project generally does not care about what you see in your web browser. It seems as if though, your either confused about how a web browser works or web scraping in general. Webpages can use different web technologies to manipulate the [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) when being displayed in web browsers. You should view the source of the page (in your web browser) and see if that matches what you see when using this project. https://www.wikihow.com/View-Source-Code

**Comment by Krylanc3lo** [comment]
Sorry @pro-src, I am sorry I thought it was related to the scrapper and how it was retrieving the information.
I will close the thread

**Comment by pro-src** [comment]
@Krylanc3lo Relax, you didn't know :smile:

**Comment by Krylanc3lo** [comment]
Hello,
I checked and this issue is similar to: https://stackoverflow.com/questions/29773528/python-requests-isnt-giving-me-the-same-html-as-my-browser-is

I will try to update the scrapper and check if urllib is helping.
