### ISSUE TITLE
Same script, different results from a computer to another

### ISSUE THREAD

**Issue by Krylanc3lo** [VeNoMouS/cloudflare-scrape-js2py#28]
Hello,

I think I have an issue related to headers but not sure how to fix it, in case you have an idea.

When I run the same basic script (the one in the README file), it is working on a first computer, but not in the second one.

Debut in the 1st (working):
```
< GET /series HTTP/1.1
< User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate
< Connection: close
< Upgrade-Insecure-Requests: 1
< 

> HTTP/1.1 301 Moved Permanently
> Date: Fri, 19 Apr 2019 20:10:21 GMT
> Transfer-Encoding: chunked
> Connection: close
> Cache-Control: max-age=3600
> Expires: Fri, 19 Apr 2019 21:10:21 GMT
> Location: /series
> Strict-Transport-Security: max-age=0
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 4ca1857aede899fe-EWR
> 
< GET /series HTTP/1.1
< User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate
< Connection: close
< Upgrade-Insecure-Requests: 1
< 

> HTTP/1.1 503 Service Temporarily Unavailable
> Date: Fri, 19 Apr 2019 20:10:21 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Set-Cookie: __cfduid=d263dd4b6d9235c1da141474008ea06d31555704621; expires=Sat, 18-Apr-20 20:10:21 GMT; path=/; domain=.swtest.tv; HttpOnly; Secure
> X-Frame-Options: SAMEORIGIN
> Cache-Control: no-cache
> Strict-Transport-Security: max-age=0
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 4ca1857b6b65922a-EWR
> 
```

Debug in the 2nd (not working):
```
< GET /series HTTP/1.1
< User-Agent: Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Build/NPPS25.137-93-8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate
< Connection: close
< Upgrade-Insecure-Requests: 1
< 

> HTTP/1.1 301 Moved Permanently
> Date: Fri, 19 Apr 2019 20:09:20 GMT
> Transfer-Encoding: chunked
> Connection: close
> Cache-Control: max-age=3600
> Expires: Fri, 19 Apr 2019 21:09:20 GMT
> Location: /series
> Strict-Transport-Security: max-age=0
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 4ca183fe2cf93c41-CDG
> 
< GET /series HTTP/1.1
< User-Agent: Mozilla/5.0 (Linux; Android 7.0; Moto G (5) Build/NPPS25.137-93-8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36
< Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
< Accept-Language: en-US,en;q=0.5
< Accept-Encoding: gzip, deflate
< Connection: close
< Upgrade-Insecure-Requests: 1
< 

> HTTP/1.1 503 Service Temporarily Unavailable
> Date: Fri, 19 Apr 2019 20:09:20 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: close
> Set-Cookie: __cfduid=d8bdc242657df6199c32a45d34bd43e991555704560; expires=Sat, 18-Apr-20 20:09:20 GMT; path=/; domain=.swtest.tv; HttpOnly; Secure
> X-Frame-Options: SAMEORIGIN
> Cache-Control: no-cache
> Strict-Transport-Security: max-age=0
> Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> Vary: Accept-Encoding
> Server: cloudflare
> CF-RAY: 4ca183fe9d4fcd7d-CDG
> 
```

**Comment by pro-src** [comment]
@Krylanc3lo looks like (Debug) is working to me. :rofl:  You're asking for general tech support and that's frowned upon here since you can't expect us to ***teach*** everybody on the internet. That's not what we do here. I've already told you that it's best to set those headers yourself and provided you with information on how to do so. You should review past issues.

**Comment by VeNoMouS** [comment]
@Krylanc3lo ? why did you close mate?

**Comment by Krylanc3lo** [comment]
Didn't want to bother you more than I already do ;)

**Comment by VeNoMouS** [comment]
Hardly bothering me, if there is a problem with the library would prefer to resolve

**Comment by Krylanc3lo** [comment]
hehe, I am reopening it then. I added the below headers but still not working:

```
headers = OrderedDict(
            [
                ('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0'),
                ('Accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'),
                ('Accept-Language', 'en-US,en;q=0.5'),
                ('Accept-Encoding', 'gzip, deflate'),
                ('Connection',  'close'),
                ('Upgrade-Insecure-Requests', '1')
            ]
        )
```
An example of URL: https://www.gktorrent.net/torrents/series

**Comment by VeNoMouS** [comment]
@Krylanc3lo the first one isn'ting working as the last request gets hit with a http 503 code...

how ever I can confirm there is something wrong happening with that site... I am investigating to try and resolve it...

**Comment by VeNoMouS** [comment]
@Krylanc3lo well... that was fun (NOT), are you using py2 or py3 ....

can you check if you have have the package `asn1crypto` installed in pip

```
pip2 freeze | grep asn1crypto
```

or 

```
pip3 freeze | grep asn1crypto
```

**Comment by VeNoMouS** [comment]
Actually further investigation we have found the root cause @Krylanc3lo

**Comment by VeNoMouS** [comment]
@Krylanc3lo can you check this please...

```
>>> import cryptography
>>> cryptography.__version__
```

Let me know the version.

**Comment by Krylanc3lo** [comment]
Sure, here you are:

On the 1st computer:
```
>>> import cryptography
>>> cryptography.__version__
'2.3'
```

On the 2nd computer:
```
>>> import cryptography
>>> cryptography.__version__
'1.2.3'

```

I guess I have to update ;)

**Comment by VeNoMouS** [comment]
@Krylanc3lo 

```
pip install cryptography==2.4.0
```

Let me know how you go.

**Comment by Krylanc3lo** [comment]
Still the same:

```
Traceback (most recent call last):
  File "/home/krylancelo/bin/dl_scripts/test.py", line 6, in <module>
    print(scraper.get("https://www.gktorrent.net/torrents/series").content)  # => "<!DOCTYPE html><html><head>..."
  File "/usr/local/lib/python3.5/dist-packages/requests-2.21.0-py3.5.egg/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cfscrape-2.0.3-py3.5.egg/cfscrape/__init__.py", line 107, in request
  File "/usr/local/lib/python3.5/dist-packages/cfscrape-2.0.3-py3.5.egg/cfscrape/__init__.py", line 160, in solve_cf_challenge
  File "/usr/local/lib/python3.5/dist-packages/cfscrape-2.0.3-py3.5.egg/cfscrape/__init__.py", line 100, in request
  File "/usr/local/lib/python3.5/dist-packages/cfscrape-2.0.3-py3.5.egg/cfscrape/__init__.py", line 64, in is_cloudflare_challenge
ValueError: Captcha

```

**Comment by VeNoMouS** [comment]
@Krylanc3lo send me an email i'll invite you to my discord and you can be our test bitch ;P

**Comment by lukele** [comment]
@VeNoMouS Did you make progress on this one? I'm seeing some interesting behavior, where if Charles Proxy (macOS SSL Proxy/Intercept) is enabled, it works. If however Charles Proxy is disabled, I get the ValueErrror: Captcha. And it reproduces 100%. Charles Proxy on, it works, Charles Proxy off, captcha. No other changes what so ever.

**Comment by VeNoMouS** [comment]
Yea I do have a theory behind whats going

**Comment by lukele** [comment]
@VeNoMouS ah interesting. To add a little more insight of what I have found. If I perform the initial request with plain urllib (python3) code, no captcha ever comes up, even if I use the requests library to send the challenge response. If however I use the requests library for the initial request and submit the challenge response with plain urllib code, I receive the captcha. Headers and header order is always the same.

**Comment by VeNoMouS** [comment]
I will try find some time this weekend to try and work it out.

**Comment by VeNoMouS** [comment]
LOL... I worked it out... I think..

**Comment by VeNoMouS** [comment]
Maybe... I didn't as i tested my code without and im getting 200's back... man I hate when it does this ;P makes testing a pain in the arse... i'll test it again later.

**Comment by VeNoMouS** [comment]
I really shouldn't do this crap at 0230 in the morning... lol... managed to make it go.. i was being retarded i tested something and forgot i did that, so i had to put it back in... anyway yea i got it going.

**Comment by VeNoMouS** [comment]
I'll test and play around with this more over the weekend just to make sure, but it looks like its working to me..

**Comment by lukele** [comment]
@VeNoMouS i‘ll send you my test code later as well. Excited in seeing what you have coming up with

**Comment by VeNoMouS** [comment]
yea sweet as, anyway imma catch some tv before bed, its almost 3am here, NZST > * :p

**Comment by pro-src** [comment]
If the proxy is to blame, you should be able to configure your browser to use the proxy and reproduce the problem in the browser. But then again... It could just be a blacklisted IP, I would not consider the ip-tracker.org service definitive but https://www.ip-tracker.org/blacklist-check.php

**Comment by Krylanc3lo** [comment]
I digged a little bit and I only have the issue with https, not http. Maybe related to certificate then

**Comment by lukele** [comment]
@VeNoMouS from my tests it appears that if the requests ciphers are updated not to include the 'ECDH+AESGCM' cipher from the default ciphers in urllib3's ssl_  cloudflare works with basically any user agent passed from @pro-src list in cloudscraper

**Comment by pro-src** [comment]
@lukele Have you tried leaving that cipher suite in the list and changing the order instead?

**Comment by pro-src** [comment]
@lukele It would make sense for browsers to report that as a supported cipher suite as well since they're using openssl which supports it but they probably send it in a different order.

https://www.chromium.org/Home/chromium-security/education/tls#TOC-Cipher-Suites
> TLS connections negotiate a cipher suite which determines how data is encrypted and authenticated. Server products typically leave configuring this to the administrator. Many cipher suites available in TLS are obsolete and, while currently supported by Chrome, are not recommended. If an obsolete cipher suite is used, Chrome may display this message when clicking the lock icon:

>“Your connection to example.com is encrypted with obsolete cryptography.”

>To avoid this message, use TLS 1.2 and prioritize an ECDHE cipher suite with AES_128_GCM or CHACHA20_POLY1305. Most servers will wish to negotiate TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.

**Comment by pro-src** [comment]
If you're interested to know the default cipher suite list that chromium uses, you should be able to find that in this repo: https://github.com/google/boringssl
Since chromium uses a fork of openssl called openssl and supports extra ciphers i.e. https://github.com/chromium/chromium/tree/master/third_party/boringssl/linux-x86_64/crypto

**Comment by lukele** [comment]
Thanks for the links!

Interestingly, changing the order doesn't help. Still not sure how the ciphers matter exactly, but they seem to be the last piece of the puzzle. With the default ciphers from urllib3 and ECDH+AESGCM removed it seems to consistently work.

working list: TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:ECDH+CHACHA20:DH+AESGCM:DH+CHACHA20:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!eNULL:!MD5

**Comment by pro-src** [comment]
@lukele I've got a lot more of those links, join the discord channel :stuck_out_tongue_closed_eyes: 
Your list seems to be the best option we have atm since don't won't to unnecessarily remove support for other cipher suites. I think we should be able to match the UA's cipher suite list and order exactly. I'm pretty sure that the cipher suite order changes for mobile UA's which prioritize CHACHA20.

**Comment by pro-src** [comment]
Right so instead of digging through source on a per UA basis: https://www.ssllabs.com/ssltest/viewMyClient.html
User-Agent: `User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36`
<details><summary>Results (Click to expand)</summary>


Cipher Suites (in order of preference)
---
TLS_GREASE_0A (0xa0a) | -
TLS_AES_128_GCM_SHA256 (0x1301)   Forward Secrecy | 128
TLS_AES_256_GCM_SHA384 (0x1302)   Forward Secrecy | 256
TLS_CHACHA20_POLY1305_SHA256 (0x1303)   Forward Secrecy | 256
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy | 128
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy | 128
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   Forward Secrecy | 256
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)   Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)   Forward Secrecy | 256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   Forward Secrecy | 128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   Forward Secrecy | 256
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)   WEAK | 128
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)   WEAK | 256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   WEAK | 128
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)   WEAK | 256
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   WEAK | 112
(1) When a browser supports SSL 2, its SSL 2-only suites are shown only on the very first connection to this site. To see the suites, close all browser windows, then open this exact page directly. Don't refresh.

Protocol Details
--
Server Name Indication (SNI) | Yes
Secure Renegotiation | Yes
TLS compression | No
Session tickets | Yes
OCSP stapling | Yes
Signature algorithms | SHA256/ECDSA,	RSA_PSS_SHA256,	SHA256/RSA,	SHA384/ECDSA,	RSA_PSS_SHA384, SHA384/RSA,	RSA_PSS_SHA512,	SHA512/RSA,	SHA1/RSA
Named Groups | tls_grease_0a0a,	x25519,	secp256r1,	secp384r1
Next Protocol Negotiation | No
Application Layer Protocol Negotiation | Yes   h2 http/1.1
SSL 2 handshake compatibility | No
</details>

**Comment by VeNoMouS** [comment]
@lukele `EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH` is better... just saying..

**Comment by pro-src** [comment]
@VeNoMouS :thinking: Isn't the smaller list removing support for a lot other cipher suites?

**Comment by VeNoMouS** [comment]
look @ what chrome establishes...

**Comment by VeNoMouS** [comment]
Lets dig out chrome source and review their lists.

**Comment by pro-src** [comment]
@VeNoMouS just use Cloudscraper to fetch https://www.ssllabs.com/ssltest/viewMyClient.html and compare the results with the ones that I just provided.

**Comment by pro-src** [comment]
I see what you're saying about what chrome establishes (meaning when chrome establishes a connection to CF) but Cloudscraper isn't meant to only ever connect to CF's servers and a smaller list means less support. Also, CF could begin to check for lack of support on a per UA basis sorta like what they're already doing for headers but for SSL ciphers, right? I'm not sure how long this has been a problem and if they're willing to adapt it but we're probably better off just matching the UA (generally).

**Comment by pro-src** [comment]
Hmm... This is a comparison between chromium and nodejs (cloudscraper.js): https://gist.github.com/pro-src/99e0318814118dc9e60d989375b3d3d9/revisions

**Comment by VeNoMouS** [comment]
![image](https://user-images.githubusercontent.com/597545/56858143-9c1d0000-69c9-11e9-8d22-1a60412b706a.png)

**Comment by VeNoMouS** [comment]
Looking at ssl labs.. of chrome..

![image](https://user-images.githubusercontent.com/597545/56858713-fb334280-69d2-11e9-981a-9e1d3aa264b0.png)

Making the exact cipher suite order ...

```
       ciphers = \
            'GREASE_3A:AES128-GCM-SHA256:AES256-GCM-SHA256:CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256' \
            ':ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305-SHA256' \
            ':ECDHE-RSA-CHACHA20-POLY1305-SHA256:ECDHE-RSA-AES128-CBC-SHA:ECDHE-RSA-AES256-CBC-SHA:RSA-AES128-GCM-SHA256' \
            ':RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:RSA-AES256-SHA:3DES-EDE-CBC'
```

**Comment by pro-src** [comment]
The default cipher list varies by CPU capabilities which is why we're getting different results. So basically, `cpu` * `openssl version` * `browser version` equals a whole lot of different default cipher lists, assuming that the browser adjusts what would be the default cipher list (reorder or otherwise). So there isn't one specific list to match... IDK what a better list would be without data mining. @VeNoMouS Are you opting to use that list as it stands?

**Comment by VeNoMouS** [comment]
Can you screen shot a ssl labs cipher list from your end for me @pro-src ?

**Comment by pro-src** [comment]
<details><summary>Without mounting an HTTPS adapter</summary>

![localhost_8000_output html](https://user-images.githubusercontent.com/34285059/56858973-6df7db80-6949-11e9-8f7c-59bf935097dc.png)
![localhost_8000_output html (1)](https://user-images.githubusercontent.com/34285059/56858972-6a645480-6949-11e9-9b78-677efe948b31.png)
![localhost_8000_output html (2)](https://user-images.githubusercontent.com/34285059/56858970-6801fa80-6949-11e9-89a9-08cb48e814bd.png)
</details>
<details><summary>With the ciphers specified</summary>

`OpenSSL.SSL.Error: [('SSL routines', 'ssl_cipher_process_rulestr', 'invalid command')]`
</details>

**Comment by VeNoMouS** [comment]
@pro-src i'll post some code in a bit for you to try just busy atm

**Comment by pro-src** [comment]
@codemanki You might want to follow this issue as I'm betting that CF will eventually update this in a way that affects your project if it's not already...

**Comment by VeNoMouS** [comment]
@pro-src i have pushed some new code for you to test.

**Comment by VeNoMouS** [comment]
@Krylanc3lo check your email for our new dev branch details

**Comment by Krylanc3lo** [comment]
I think I did not receive it. I sent you a mail

**Comment by VeNoMouS** [comment]
@Krylanc3lo def sent it to you , replied to your email, and also replied to the same email for discord invite. that time...

**Comment by VeNoMouS** [comment]
@Krylanc3lo just replied to your gmail test.

**Comment by VeNoMouS** [comment]
Project has been superseded by my other project ["cloudscraper"](https://pypi.org/project/cloudscraper/) the new git repo can be found [here](https://github.com/VeNoMouS/cloudscraper).
