### ISSUE TITLE
Unused global variable

### ISSUE THREAD

**Issue by pro-src** [VeNoMouS/cloudflare-scrape-js2py#3]
I'm not sure if this was ever used. I'd have to check the git history.

https://github.com/VeNoMouS/cloudflare-scrape-js2py/blob/7d513463c92524a6d4c4f835f562733f9203c628/cfscrape/__init__.py#L40

I think thats all of the issues that I'm aware of at the moment.

**Comment by VeNoMouS** [comment]
Removed.
