### ISSUE TITLE
Breaking challenge backwards compatibility

### ISSUE THREAD

**Issue by pro-src** [VeNoMouS/cloudflare-scrape-js2py#4]
Cloudflare doesn't exactly retire old challenges as soon as they release a new one. They keep rotating them under certain mostly unknown conditions. You can't be sure that the new "s" query param will always be there or that it's safe to add an empty query param when it's missing.

https://github.com/VeNoMouS/cloudflare-scrape-js2py/blob/7d513463c92524a6d4c4f835f562733f9203c628/cfscrape/__init__.py#L94

**Comment by pro-src** [comment]
Also, I think it's only a matter of time before Cloudflare starts changing the param order on a per request basis. Did you know that Cloudflare has a JS based bot-filter that is way better than this one but for some odd reason they only use it in conjunction with CAPTCHA?

**Comment by pro-src** [comment]
@VeNoMouS cloudscraper has maintained backwards compatibility since 2014. It has great tests that include fixtures, etc.

**Comment by pro-src** [comment]
@VeNoMouS I think the bulk of this covered by the dev branch now. I'm going to close this in preference of #13 which is really about the same thing. You can always open back up if I'm mistaken. :wink:

**Comment by VeNoMouS** [comment]
ah rgr... i'm just playing around with #7... though i don't like how it looks ... just seems "cheap".... i dont like implementation 

```
    def set_cloudflare_challenge_delay(self, delay):
        if delay > 0:
            self.delay = delay
```
```
    def solve_cf_challenge(self, resp, **original_kwargs):
        body = resp.text

        # Cloudflare requires a delay before solving the challenge
        if self.delay == 8:
            try:
                delay = float(re.search(r'submit\(\);\r?\n\s*},\s*([0-9]+)', body).group(1)) / float(1000) 
                if delay in range(1,10):
                    self.delay = delay
            except:
                pass
                
        sleep(self.delay) 
```
