### ISSUE TITLE
Cloudflare challenge can be sent with HTTP status 429 - Too Many Requests

### ISSUE THREAD

**Issue by pro-src** [VeNoMouS/cloudflare-scrape-js2py#6]
The good news is that you don't have to respect the `Retry-After` header as of right now.
https://github.com/VeNoMouS/cloudflare-scrape-js2py/blob/7d513463c92524a6d4c4f835f562733f9203c628/cfscrape/__init__.py#L58

**Comment by VeNoMouS** [comment]
Added into PR b21ba1d696fb4108a1b62ebe326bbcbb3585efc3

**Comment by VeNoMouS** [comment]
lol i think is the first ticket of yours ive been able to close LOL <3
