### ISSUE TITLE
Allow library users to specify the timeout

### ISSUE THREAD

**Issue by pro-src** [VeNoMouS/cloudflare-scrape-js2py#7]
You can emit a warning if you fail to parse the timeout in this case. The regex is really loose.
https://github.com/VeNoMouS/cloudflare-scrape-js2py/blob/7d513463c92524a6d4c4f835f562733f9203c628/cfscrape/__init__.py#L80

Also, if this parses the wrong number, it could wait for a very long time. Probably should check to see if it's excessive and if the user didn't specify a timeout then raise an exception.

**Comment by VeNoMouS** [comment]
744fda03571d5ca5789f57e0c74ee4bc9421a265 via the function `set_cloudflare_challenge_delay`
