### ISSUE TITLE
No module named js2py.pyjs

### ISSUE THREAD

**Issue by sennz** [VeNoMouS/cloudflare-scrape-js2py#9]
I am getting below error, how can i fix 

                                             js2py\evaljs.py", line 147, in __init__
                                                exec (DEFAULT_HEADER, self._context)
                                              File "<string>", line 1, in <module>
                                            ImportError: No module named js2py.pyjs

**Comment by VeNoMouS** [comment]
install js2py?

**Comment by sennz** [comment]
Yes.

**Comment by VeNoMouS** [comment]
Via pip? are you using python 2 or 3? did you use pip3 if using python3?

**Comment by VeNoMouS** [comment]
That error looks to be a js2py error to me as well..

**Comment by sennz** [comment]
Downloaded directly. Python 2

**Comment by VeNoMouS** [comment]
i'd give pip a try mate

**Comment by sennz** [comment]
I will try. Thanks

**Comment by VeNoMouS** [comment]
@sennz how did you go mate?

**Comment by sennz** [comment]
It is working with python 3
